export const baseLanguages  = {
    en:{
        signIn:"Sign In",
        email:"Email",
        password:"Password",
        forgot:"Forgot your password?",
        forgotQuery:"Enter your email address and we'll send you a code to help you reset your password.",
        reset:"Send reset code",
        back:"Back",
        createAccount:"Create an account",
        uppercase: 'At least one uppercase letter' ,
        lowercase: 'At least one lowercase letter' ,
        digit: 'At least one digit' ,
        special: 'At least one special character' ,
        minLength: 'Should be more than 8 characters' ,
        maxLength: 'Should be less than 16 characters',
        enterValidEmail: "Please enter a valid email or create an account",
        enterReset:"Enter received code",
        checkEmail:"Please check your email",
        forCode:"for a reset code and create a new password.",
        verificationError:"Please enter correct reset code.",
        createPassword:"Create new password",
        reenter:"Re-enter the password",
        noMatch:"Passwords do not match",
        helperText:"Your password must have the following:",
        firstName:"First Name",
        lastName:"Last Name",
        phoneNumber: "Phone number",
        passwordRequirements: "Your password must have the following:",
        confirmPassword: "Confirm Password",
        signUp: "Sign Up",
        verifyAccount: "Verify Account",
        emailCheck: "Please check your email for a confirmation code. This may take several minutes.",
        invalidCode: "Invalid verification code provided, please try again.",
        newCode: "New verification code sent successfully.",
        noCode: "Didn't receive your verification code?",
        resend: "Resend Code",
        verify: "Verify",
        enterPassword: "Enter new password",
        setPassword: "Set Password",
        accountExists: "An account with the given email already exists.",
        validEmail: "Please enter a valid email.",
        passwordReset: "Password Reset",
        setNewPassword: "Set New Password",
        siteOwnership: "Change site ownership permissions by Site Manager",
        updateSitesManaged: "Update sites managed",
        createNewSite: "Create new site",
        editSelectedSite: "Edit selected sites",
        deleteSelectedSites: "Delete selected sites",
        createNewSiteDialog: "To create a new Site, enter the relevant details and press create",
        editSiteDialog: "To edit this site, fill in the details and press Edit",
        create: "Create",
        cancel: "Cancel",
        deleteSiteWarning: "WARNING: This will delete all associated customers and site managers",
        name: "Name",
        serviceRadius: "Radius (Km)",
        latitude: "Latitude",
        longitude: "Longitude",
        description: "Description",
        cognitoID: "Cognito ID",
        givenName: "Given Name",
        familyName: "Family Name",
        siteName: "Site name",
        siteDescription: "Site Description",
        smsDescription: "SMS description",
        avgWaitMinute: "Average Wait time (minutes)",
        avgLineCount: "Average line length",
        estimatedDaily: "Daily Total Usage (L)",
        subscriptionFee: "Subscription Fee",
        expectedJerrycans: "Expected Jerrycans",
        nickname: "Nickname",
        updatePassword: "Update Password",
        verificationCode: "Didn't receive your verification code?",
        resendCode: "Resend Code",
        or: "or",
        siteID: "Site ID",
        customerID: "Customer ID",
        languageCode: "Language code",
        languageName: "Language Name",
        addNewLanguage: "Add new language",
        syncLanguageToCloud: "Sync Language to Cloud",
        addLanguageTemplate: "Add new language template (does not upload until you finish submit phrases)",
        english: "English Phrase",
        translation: "Translated Phrase",
        deleteLanguageTemplate: "Delete selected language?",
        add: "Add",
        delete: "Delete",
        language: "Language",
    },
    sw: {
        signIn:"Weka sahihi ",
        email:"Barua pepe",
        password:"Nenosiri",
        forgot:"Umesahau nenosiri yako?",
        forgotQuery:"Weka barua pepe yako na tutakutumia msimbo ili kukusaidia kuweka upya nenosiri lako.",
        reset:"Tuma msimbo wa kuweka upya",
        back:"Nyuma",
        createAccount:"Fungua akaunti",
        uppercase: 'Angalau herufi kubwa moja' ,
        lowercase: 'Angalau herufi ndogo moja' ,
        digit: 'Angalau tarakimu moja' ,
        special: 'Angalau mhusika mmoja maalum' ,
        minLength: 'Inapaswa kuwa zaidi ya herufi 8' ,
        maxLength: 'Inapaswa kuwa chini ya herufi 16',
        enterValidEmail: "Tafadhali ingiza barua pepe halali au ufungue akaunti",
        enterReset:"Weka msimbo uliopokelewa",
        checkEmail:"Tafadhali angalia barua pepe yako ",
        forCode:"kwa msimbo wa kuweka upya na unda nenosiri mpya.",
        verificationError:"Tafadhali weka msimbo sahihi wa kuweka upya.",
        createPassword:"Unda nenosiri mpya",
        reenter:"Ingiza tena nenosiri",
        noMatch:"Manenosiri hayalingani",
        helperText:"Nenosiri lako lazima liwe na yafuatayo:",
        firstName:"Jina la kwanza",
        lastName:"Jina la familia",
        passwordRequirements: "Nenosiri lako lazima liwe na yafuatayo:",
        confirmPassword: "Thibitisha Nenosiri",
        signUp: "Jisajili",
        verifyAccount: "Thibitisha Akaunti",
        emailCheck: "Tafadhali angalia barua pepe yako kwa nambari ya kuthibitisha. Hii inaweza kuchukua dakika kadhaa.",
        invalidCode: "Nambari ya kuthibitisha imetolewa, tafadhali jaribu tena.",
        newCode: "Nambari mpya ya uthibitishaji imetumwa kwa mafanikio.",
        noCode: "Hukupokea nambari yako ya kuthibitisha?",
        resend: "Tuma tena Msimbo",
        verify: "Thibitisha",
        enterPassword: "Weka nenosiri jipya",
        setPassword: "Weka Nenosiri",
        accountExists: "Akaunti iliyo na barua pepe uliyopewa tayari ipo.",
        validEmail: "Tafadhali weka barua pepe halali.",
        passwordReset: "Weka Upya Nenosiri",
        setNewPassword: "Weka Nenosiri Jipya",
        siteOwnership: "Badilisha ruhusa za umiliki wa tovuti na Msimamizi wa Tovuti",
        updateSitesManaged: "Sasisha tovuti zinadhibitiwa",
        createNewSite: "Unda tovuti mpya",
        editSelectedSite: "Unda tovuti mpya",
        deleteSelectedSites: "Futa tovuti zilizochaguliwa",
        createNewSiteDialog: "Ili kuunda Tovuti mpya, weka maelezo muhimu na ubonyeze unda",
        editSiteDialog: "Ili kuhariri tovuti hii, jaza maelezo na ubonyeze Hariri",
        create: "Unda",
        cancel: "Ghairi",
        deleteSiteWarning: "ONYO: Hii itafuta wateja wote wanaohusishwa na wasimamizi wa tovuti",
        name: "Jina",
        serviceRadius: "Kipenyo (Km)",
        latitude: "Latitudo",
        longitude: "Longitude",
        description: "Maelezo",
        cognitoID: "Cognito ID",
        givenName: "Jina Lililopewa",
        familyName: "Jina la ukoo",
        siteName: "Jina la tovuti",
        siteDescription: "Maelezo ya Tovuti",
        smsDescription: "Maelezo ya sms",
        avgWaitMinute: "Muda wa wastani wa Kusubiri (dakika)",
        avgLineCount: "Urefu wa wastani wa mstari",
        estimatedDaily: "Jumla ya Matumizi ya Kila Siku (L)",
        subscriptionFee: "Ada ya Usajili",
        expectedJerrycans: "Wanaotarajiwa wa Jerrycans",
        nickname: "Jina la utani",
        updatePassword: "Sasisha Nenosiri",
        verificationCode: "Hukupokea nambari yako ya kuthibitisha?",
        resendCode: "Tuma tena Msimbo",
        or: "au",
        siteID: "Kitambulisho cha tovuti",
        customerID: "Kitambulisho cha Mteja",
        languageCode: "Msimbo wa lugha",
        languageName: "Jina la Lugha",
        addNewLanguage: "Ongeza lugha mpya",
        syncLanguageToCloud: "Sawazisha Lugha kwa Wingu",
        addLanguageTemplate: "Ongeza kiolezo cha lugha mpya (haipakii hadi umalize kuwasilisha misemo)",
        english: "Neno la Kiingereza",
        translation: "Neno lililotafsiriwa",
        deleteLanguageTemplate: "Je, ungependa kufuta lugha uliyochagua?",
        add: "Ongeza",
        delete: "Futa",
        language: "Lugha",
    }
}
export const baseAssociations = [
    {id: "en", language: "English"},
    {id: "sw", language: "Swahili"},
]